name: Deploy Resource Management package

on:
  workflow_dispatch:
    inputs:
      version:
        description: Package version
        required: true
        type: string

jobs:
  publish:
    uses: ./.github/workflows/deploy_package.yml
    with:
      project-path: Shed.ResourceManagement/Shed.ResourceManagement.csproj
      version: ${{ inputs.version }}