name: Run unit tests on PR

on:
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  packages: read

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v6

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.x'
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}

    - uses: godot-gdunit-labs/gdUnit4-action@v1
      with:
        godot-version: '4.7.0'
        project_dir: './Shed.LateInjection.Godot/'
        paths: 'res://'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build