name: Run unit tests on PR

on:
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  packages: read

env:
  GODOT_BIN: /home/runner/bin/godot

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v6

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.x'
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}

    - name: Install Godot Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libvulkan1 mesa-vulkan-drivers libx11-dev libxcursor-dev libxinerama-dev libxrandr-dev libxi-dev libglx-dev

    - uses: chickensoft-games/setup-godot@v2
      name: 🤖 Setup Godot
      with:
        version: 4.7.0
        use-dotnet: true
    
    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --settings .runsettings