name: Run unit tests on PR

on:
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  packages: read

env:
  GODOT_BIN: /home/runner/godot-linux

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v6

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.x'
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}

    - uses: godot-gdunit-labs/gdUnit4-action/.gdunit4_action/godot-install@v1
      name: Install Godot
      with:
        godot-version: 4.7.0
        godot-net: true
        godot-status-version: stable
        install-path: '/home/runner/godot-linux'
    
    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build